// GENERATED by scripts/gen-rpc.ts — edit the manifest there, then bun run gen:rpc
import { createServerFn } from "@tanstack/react-start";

import type * as flashcardsImpl from "./flashcards";
import type * as indexContentImpl from "./index-content";
import type * as itemsImpl from "./items";
import type * as queriesImpl from "./queries";
import type * as reviewImpl from "./review";
import type * as settingsImpl from "./settings";
import type * as versionImpl from "./version";

// RPC layer between client code and the server-only implementations. Each
// exported function keeps the exact signature of its implementation (callers
// are unchanged from the Next.js server-action days); the createServerFn
// handlers dynamically import the impl modules so db/pdf/etc. code never
// reaches the client bundle. Thrown ActionError/UnauthorizedError messages
// serialize across the wire, so mutation error toasts behave as before.

// --- items ---

const searchItemsFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof itemsImpl.searchItems>) => args)
  .handler(({ data }) => import("./items").then((m) => m.searchItems(...data)));
export const searchItems: typeof itemsImpl.searchItems = (...args) =>
  searchItemsFn({ data: args });

const deleteItemFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof itemsImpl.deleteItem>) => args)
  .handler(({ data }) => import("./items").then((m) => m.deleteItem(...data)));
export const deleteItem: typeof itemsImpl.deleteItem = (...args) =>
  deleteItemFn({ data: args });

const fetchPageTitleFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof itemsImpl.fetchPageTitle>) => args)
  .handler(({ data }) =>
    import("./items").then((m) => m.fetchPageTitle(...data)),
  );
export const fetchPageTitle: typeof itemsImpl.fetchPageTitle = (...args) =>
  fetchPageTitleFn({ data: args });

const createItemFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof itemsImpl.createItem>) => args)
  .handler(({ data }) => import("./items").then((m) => m.createItem(...data)));
export const createItem: typeof itemsImpl.createItem = (...args) =>
  createItemFn({ data: args });

const updateItemFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof itemsImpl.updateItem>) => args)
  .handler(({ data }) => import("./items").then((m) => m.updateItem(...data)));
export const updateItem: typeof itemsImpl.updateItem = (...args) =>
  updateItemFn({ data: args });

const setItemReadFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof itemsImpl.setItemRead>) => args)
  .handler(({ data }) => import("./items").then((m) => m.setItemRead(...data)));
export const setItemRead: typeof itemsImpl.setItemRead = (...args) =>
  setItemReadFn({ data: args });

const generateItemPreviewFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof itemsImpl.generateItemPreview>) => args)
  .handler(({ data }) =>
    import("./items").then((m) => m.generateItemPreview(...data)),
  );
export const generateItemPreview: typeof itemsImpl.generateItemPreview = (
  ...args
) => generateItemPreviewFn({ data: args });

// --- queries ---

const fetchItemsFn = createServerFn({ method: "POST" }).handler(() =>
  import("./queries").then((m) => m.fetchItems()),
);
export const fetchItems: typeof queriesImpl.fetchItems = () => fetchItemsFn();

const fetchItemPreviewsFn = createServerFn({ method: "POST" }).handler(() =>
  import("./queries").then((m) => m.fetchItemPreviews()),
);
export const fetchItemPreviews: typeof queriesImpl.fetchItemPreviews = () =>
  fetchItemPreviewsFn();

// --- settings ---

const getSettingsFn = createServerFn({ method: "POST" }).handler(() =>
  import("./settings").then((m) => m.getSettings()),
);
export const getSettings: typeof settingsImpl.getSettings = () =>
  getSettingsFn();

const updateSettingsFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof settingsImpl.updateSettings>) => args)
  .handler(({ data }) =>
    import("./settings").then((m) => m.updateSettings(...data)),
  );
export const updateSettings: typeof settingsImpl.updateSettings = (...args) =>
  updateSettingsFn({ data: args });

// --- flashcards ---

const getAllFlashcardsFn = createServerFn({ method: "POST" }).handler(() =>
  import("./flashcards").then((m) => m.getAllFlashcards()),
);
export const getAllFlashcards: typeof flashcardsImpl.getAllFlashcards = () =>
  getAllFlashcardsFn();

const updateFlashcardFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof flashcardsImpl.updateFlashcard>) => args)
  .handler(({ data }) =>
    import("./flashcards").then((m) => m.updateFlashcard(...data)),
  );
export const updateFlashcard: typeof flashcardsImpl.updateFlashcard = (
  ...args
) => updateFlashcardFn({ data: args });

// --- reviews ---

const rateCardFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof reviewImpl.rateCard>) => args)
  .handler(({ data }) => import("./review").then((m) => m.rateCard(...data)));
export const rateCard: typeof reviewImpl.rateCard = (...args) =>
  rateCardFn({ data: args });

// --- index ---

const semanticSearchFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof indexContentImpl.semanticSearch>) => args)
  .handler(({ data }) =>
    import("./index-content").then((m) => m.semanticSearch(...data)),
  );
export const semanticSearch: typeof indexContentImpl.semanticSearch = (
  ...args
) => semanticSearchFn({ data: args });

const reindexItemFn = createServerFn({ method: "POST" })
  .validator((args: Parameters<typeof indexContentImpl.reindexItem>) => args)
  .handler(({ data }) =>
    import("./index-content").then((m) => m.reindexItem(...data)),
  );
export const reindexItem: typeof indexContentImpl.reindexItem = (...args) =>
  reindexItemFn({ data: args });

// --- version ---

const getVersionInfoFn = createServerFn({ method: "POST" }).handler(() =>
  import("./version").then((m) => m.getVersionInfo()),
);
export const getVersionInfo: typeof versionImpl.getVersionInfo = () =>
  getVersionInfoFn();
