// Generated by scripts/mac-tokens.ts (bun run mac:tokens) from app/globals.css. Do not edit.
//
// Every oklch colour the stylesheet defines for both appearances, and the
// radii and row heights. Theme.swift keeps the rest.

import SwiftUI

extension Theme {
    // MARK: Colours

    static let background = dynamic(oklch(0.985, 0.002, 80), oklch(0.18, 0.0035, 70))
    static let foreground = dynamic(oklch(0.22, 0.004, 70), oklch(0.96, 0.003, 80))
    static let card = dynamic(oklch(0.97, 0.0025, 80), oklch(0.215, 0.004, 70))
    static let cardForeground = dynamic(oklch(0.22, 0.004, 70), oklch(0.96, 0.003, 80))
    static let surface = dynamic(oklch(0.995, 0.0015, 80), oklch(0.24, 0.004, 70))
    static let popover = dynamic(oklch(0.985, 0.002, 80), oklch(0.215, 0.004, 70))
    static let popoverForeground = dynamic(oklch(0.22, 0.004, 70), oklch(0.96, 0.003, 80))
    static let primary = dynamic(oklch(0.575, 0.195, 258), oklch(0.76, 0.11, 260))
    static let primaryForeground = dynamic(oklch(0.985, 0.002, 80), oklch(0.2, 0.04, 260))
    static let secondary = dynamic(oklch(0.935, 0.003, 80), oklch(0.29, 0.004, 70))
    static let secondaryForeground = dynamic(oklch(0.24, 0.004, 70), oklch(0.96, 0.003, 80))
    static let muted = dynamic(oklch(0.95, 0.0025, 80), oklch(0.27, 0.004, 70))
    static let mutedForeground = dynamic(oklch(0.52, 0.005, 70), oklch(0.7, 0.006, 75))
    static let accent = dynamic(oklch(0.92, 0.003, 80), oklch(0.31, 0.004, 70))
    static let accentForeground = dynamic(oklch(0.24, 0.004, 70), oklch(0.96, 0.003, 80))
    static let badge = dynamic(oklch(0.935, 0.003, 80), oklch(0.29, 0.004, 70))
    static let badgeForeground = dynamic(oklch(0.24, 0.004, 70), oklch(0.96, 0.003, 80))
    static let starred = dynamic(oklch(0.75, 0.145, 85), oklch(0.82, 0.15, 88))
    static let link = dynamic(oklch(0.55, 0.16, 250), oklch(0.72, 0.14, 245))
    static let destructive = dynamic(oklch(0.59, 0.19, 27), oklch(0.64, 0.175, 25))
    static let destructiveForeground = dynamic(oklch(0.985, 0.002, 85), oklch(0.985, 0.002, 85))
    static let border = dynamic(oklch(0.9, 0.003, 80), oklch(0.29, 0.004, 70))
    static let input = dynamic(oklch(0.9, 0.003, 80), oklch(0.315, 0.004, 70))
    static let ring = dynamic(oklch(0.7, 0.005, 75), oklch(0.55, 0.01, 75))
    static let toastErrorBackground = dynamic(oklch(0.97, 0.015, 25), oklch(0.25, 0.04, 25))
    static let toastErrorText = dynamic(oklch(0.45, 0.18, 25), oklch(0.8, 0.14, 25))
    static let toastErrorBorder = dynamic(oklch(0.9, 0.04, 25), oklch(0.35, 0.06, 25))
    static let selection = dynamic(oklch(0.85, 0.07, 258, alpha: 0.5), oklch(0.5, 0.1, 258, alpha: 0.55))
    static let selectionForeground = dynamic(oklch(0.22, 0.004, 70), oklch(0.96, 0.003, 80))
    static let primaryBorder = dynamic(oklch(0.53, 0.18, 258), oklch(0.64, 0.12, 259))

    // MARK: Shape and density

    static let radiusControl: CGFloat = 10
    static let radiusSurface: CGFloat = 20
    static let rowHeight: CGFloat = 26
    static let sidebarRowHeight: CGFloat = 24
}
