import type { Metadata } from "next";
import { Suspense } from "react";
import { headers } from "next/headers";
import "@fontsource-variable/dm-sans";
import "./globals.css";
import { AuthWatcher } from "@/components/auth-watcher";
import { DeepLinkItemWatcher } from "@/components/deep-link-item-watcher";
import { ElectronZoomWatcher } from "@/components/electron-zoom-watcher";
import { ItemsSyncWatcher } from "@/components/items-sync-watcher";
import { QueryProvider } from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { TOOLTIP_DELAY_MS } from "@/components/ui/tooltip-config";
import { THEME_BOOTSTRAP_SCRIPT } from "@/lib/theme-bootstrap";

export const metadata: Metadata = {
  title: "Reading List",
};

// Pin serverless/server-action execution next to the Supabase DB, which lives
// in AWS eu-west-1 (Ireland). Vercel's default region is us-east (iad1), which
// put every auth + DB round-trip across the Atlantic — the dominant cost of
// the items load on the deployed app. dub1 (Dublin) is co-located with the DB.
export const preferredRegion = "dub1";

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  // CSP nonce is generated by middleware.ts and forwarded on the request.
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Connects to the standalone React DevTools (`bun x react-devtools`)
            listening on localhost:8097. Dev-only so it never ships to prod;
            must load before React, hence the head placement. The CSP nonce
            lets it through script-src; middleware opens connect-src to the
            DevTools socket in development. */}
        {process.env.NODE_ENV === "development" && nonce && (
          // Inline loader rather than next/script: next/script's
          // beforeInteractive strategy emits its own nonce-carrying bootstrap
          // node that suppressHydrationWarning can't reach, so the
          // stripped-nonce mismatch warning fires there. This inline node keeps
          // the nonce (required by 'strict-dynamic'), honours
          // suppressHydrationWarning, and document.writes the DevTools agent
          // synchronously during head parse — before React in the body, which
          // is the ordering the hook needs. The written tag carries the nonce
          // so CSP admits it.
          <script
            nonce={nonce}
            suppressHydrationWarning
            dangerouslySetInnerHTML={{
              __html: `document.write('<script src="http://localhost:8097" nonce="${nonce}"><\\/script>')`,
            }}
          />
        )}
        {/* Browsers strip the nonce attribute from the DOM after CSP
            processing, so the client sees "" where the server rendered the
            generated nonce. That's intentional (defense against script
            gadgets) — suppress the hydration warning for this node only. */}
        <script
          nonce={nonce}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP_SCRIPT }}
        />
      </head>
      <body className="bg-background font-sans text-foreground">
        <Suspense>
          <QueryProvider>
            <AuthWatcher />
            <DeepLinkItemWatcher />
            <ElectronZoomWatcher />
            <ItemsSyncWatcher />
            <TooltipProvider delay={TOOLTIP_DELAY_MS}>
              {children}
            </TooltipProvider>
          </QueryProvider>
        </Suspense>
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
