import type { Metadata } from "next";
import { Suspense } from "react";
import { headers } from "next/headers";
import "@fontsource-variable/dm-sans";
import "./globals.css";
import { QueryProvider } from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider, TOOLTIP_DELAY_MS } from "@/components/ui/tooltip";
import { THEME_BOOTSTRAP_SCRIPT } from "@/lib/theme-bootstrap";

export const metadata: Metadata = {
  title: "Reading List",
};

const RootLayout = async ({
  children,
}: {
  children: React.ReactNode;
}) => {
  // CSP nonce is generated by middleware.ts and forwarded on the request.
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Browsers strip the nonce attribute from the DOM after CSP
            processing, so the client sees "" where the server rendered the
            generated nonce. That's intentional (defense against script
            gadgets) — suppress the hydration warning for this node only. */}
        <script
          nonce={nonce}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP_SCRIPT }}
        />
      </head>
      <body className="font-sans bg-background text-foreground">
        <Suspense>
          <QueryProvider>
            <TooltipProvider delay={TOOLTIP_DELAY_MS}>{children}</TooltipProvider>
          </QueryProvider>
        </Suspense>
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
