/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionDotjsonRouteImport } from './routes/version[.]json'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevErrorRouteImport } from './routes/dev-error'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignIndexRouteImport } from './routes/design.index'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as DesignRoundsRouteImport } from './routes/design.rounds'
import { Route as DesignComponentsRouteImport } from './routes/design.components'
import { Route as AuthReturnToAppRouteImport } from './routes/auth.return-to-app'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as ApiAskRouteImport } from './routes/api.ask'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as ApiStorageSplatRouteImport } from './routes/api.storage.$'
import { Route as ApiExtensionItemsRouteImport } from './routes/api.extension.items'

const VersionDotjsonRoute = VersionDotjsonRouteImport.update({
  id: '/version.json',
  path: '/version.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevErrorRoute = DevErrorRouteImport.update({
  id: '/dev-error',
  path: '/dev-error',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoundsRoute = DesignRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => DesignRoute,
} as any)
const DesignComponentsRoute = DesignComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DesignRoute,
} as any)
const AuthReturnToAppRoute = AuthReturnToAppRouteImport.update({
  id: '/auth/return-to-app',
  path: '/auth/return-to-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageSplatRoute = ApiStorageSplatRouteImport.update({
  id: '/api/storage/$',
  path: '/api/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionItemsRoute = ApiExtensionItemsRouteImport.update({
  id: '/api/extension/items',
  path: '/api/extension/items',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/dev-error': typeof DevErrorRoute
  '/login': typeof LoginRoute
  '/version.json': typeof VersionDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/ask': typeof ApiAskRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/return-to-app': typeof AuthReturnToAppRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/rounds': typeof DesignRoundsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/design/': typeof DesignIndexRoute
  '/api/extension/items': typeof ApiExtensionItemsRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-error': typeof DevErrorRoute
  '/login': typeof LoginRoute
  '/version.json': typeof VersionDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/ask': typeof ApiAskRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/return-to-app': typeof AuthReturnToAppRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/rounds': typeof DesignRoundsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/design': typeof DesignIndexRoute
  '/api/extension/items': typeof ApiExtensionItemsRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/dev-error': typeof DevErrorRoute
  '/login': typeof LoginRoute
  '/version.json': typeof VersionDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/ask': typeof ApiAskRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/return-to-app': typeof AuthReturnToAppRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/rounds': typeof DesignRoundsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/design/': typeof DesignIndexRoute
  '/api/extension/items': typeof ApiExtensionItemsRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/dev-error'
    | '/login'
    | '/version.json'
    | '/.well-known/oauth-protected-resource'
    | '/api/ask'
    | '/api/mcp'
    | '/auth/callback'
    | '/auth/return-to-app'
    | '/design/components'
    | '/design/rounds'
    | '/oauth/consent'
    | '/design/'
    | '/api/extension/items'
    | '/api/storage/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-error'
    | '/login'
    | '/version.json'
    | '/.well-known/oauth-protected-resource'
    | '/api/ask'
    | '/api/mcp'
    | '/auth/callback'
    | '/auth/return-to-app'
    | '/design/components'
    | '/design/rounds'
    | '/oauth/consent'
    | '/design'
    | '/api/extension/items'
    | '/api/storage/$'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/dev-error'
    | '/login'
    | '/version.json'
    | '/.well-known/oauth-protected-resource'
    | '/api/ask'
    | '/api/mcp'
    | '/auth/callback'
    | '/auth/return-to-app'
    | '/design/components'
    | '/design/rounds'
    | '/oauth/consent'
    | '/design/'
    | '/api/extension/items'
    | '/api/storage/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRouteWithChildren
  DevErrorRoute: typeof DevErrorRoute
  LoginRoute: typeof LoginRoute
  VersionDotjsonRoute: typeof VersionDotjsonRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiMcpRoute: typeof ApiMcpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthReturnToAppRoute: typeof AuthReturnToAppRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiExtensionItemsRoute: typeof ApiExtensionItemsRoute
  ApiStorageSplatRoute: typeof ApiStorageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version.json': {
      id: '/version.json'
      path: '/version.json'
      fullPath: '/version.json'
      preLoaderRoute: typeof VersionDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-error': {
      id: '/dev-error'
      path: '/dev-error'
      fullPath: '/dev-error'
      preLoaderRoute: typeof DevErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof DesignRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/rounds': {
      id: '/design/rounds'
      path: '/rounds'
      fullPath: '/design/rounds'
      preLoaderRoute: typeof DesignRoundsRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/components': {
      id: '/design/components'
      path: '/components'
      fullPath: '/design/components'
      preLoaderRoute: typeof DesignComponentsRouteImport
      parentRoute: typeof DesignRoute
    }
    '/auth/return-to-app': {
      id: '/auth/return-to-app'
      path: '/auth/return-to-app'
      fullPath: '/auth/return-to-app'
      preLoaderRoute: typeof AuthReturnToAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/$': {
      id: '/api/storage/$'
      path: '/api/storage/$'
      fullPath: '/api/storage/$'
      preLoaderRoute: typeof ApiStorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/items': {
      id: '/api/extension/items'
      path: '/api/extension/items'
      fullPath: '/api/extension/items'
      preLoaderRoute: typeof ApiExtensionItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DesignRouteChildren {
  DesignComponentsRoute: typeof DesignComponentsRoute
  DesignRoundsRoute: typeof DesignRoundsRoute
  DesignIndexRoute: typeof DesignIndexRoute
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignComponentsRoute: DesignComponentsRoute,
  DesignRoundsRoute: DesignRoundsRoute,
  DesignIndexRoute: DesignIndexRoute,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRouteWithChildren,
  DevErrorRoute: DevErrorRoute,
  LoginRoute: LoginRoute,
  VersionDotjsonRoute: VersionDotjsonRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiAskRoute: ApiAskRoute,
  ApiMcpRoute: ApiMcpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthReturnToAppRoute: AuthReturnToAppRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiExtensionItemsRoute: ApiExtensionItemsRoute,
  ApiStorageSplatRoute: ApiStorageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
