/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionDotjsonRouteImport } from './routes/version[.]json'
import { Route as VersionRouteImport } from './routes/version'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevErrorRouteImport } from './routes/dev-error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as DebugIndexRouteImport } from './routes/debug.index'
import { Route as ReviewSessionIdRouteImport } from './routes/review.$sessionId'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as DebugToastsRouteImport } from './routes/debug.toasts'
import { Route as DebugSuggestedCardsRouteImport } from './routes/debug.suggested-cards'
import { Route as DebugSpinnersRouteImport } from './routes/debug.spinners'
import { Route as DebugReviewSummaryPreviewRouteImport } from './routes/debug.review-summary-preview'
import { Route as DebugReviewSessionPreviewRouteImport } from './routes/debug.review-session-preview'
import { Route as DebugReviewDialogsRouteImport } from './routes/debug.review-dialogs'
import { Route as DebugReviewCountAnimationsRouteImport } from './routes/debug.review-count-animations'
import { Route as DebugKbdRouteImport } from './routes/debug.kbd'
import { Route as DebugEmptyStatesRouteImport } from './routes/debug.empty-states'
import { Route as DebugDesignSystemRouteImport } from './routes/debug.design-system'
import { Route as DebugCodeBlockRouteImport } from './routes/debug.code-block'
import { Route as AuthReturnToAppRouteImport } from './routes/auth.return-to-app'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as ApiAskRouteImport } from './routes/api.ask'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as ApiStorageSplatRouteImport } from './routes/api.storage.$'
import { Route as ApiExtensionItemsRouteImport } from './routes/api.extension.items'

const VersionDotjsonRoute = VersionDotjsonRouteImport.update({
  id: '/version.json',
  path: '/version.json',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionRoute = VersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevErrorRoute = DevErrorRouteImport.update({
  id: '/dev-error',
  path: '/dev-error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugIndexRoute = DebugIndexRouteImport.update({
  id: '/debug/',
  path: '/debug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSessionIdRoute = ReviewSessionIdRouteImport.update({
  id: '/review/$sessionId',
  path: '/review/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugToastsRoute = DebugToastsRouteImport.update({
  id: '/debug/toasts',
  path: '/debug/toasts',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugSuggestedCardsRoute = DebugSuggestedCardsRouteImport.update({
  id: '/debug/suggested-cards',
  path: '/debug/suggested-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugSpinnersRoute = DebugSpinnersRouteImport.update({
  id: '/debug/spinners',
  path: '/debug/spinners',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugReviewSummaryPreviewRoute =
  DebugReviewSummaryPreviewRouteImport.update({
    id: '/debug/review-summary-preview',
    path: '/debug/review-summary-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const DebugReviewSessionPreviewRoute =
  DebugReviewSessionPreviewRouteImport.update({
    id: '/debug/review-session-preview',
    path: '/debug/review-session-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const DebugReviewDialogsRoute = DebugReviewDialogsRouteImport.update({
  id: '/debug/review-dialogs',
  path: '/debug/review-dialogs',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugReviewCountAnimationsRoute =
  DebugReviewCountAnimationsRouteImport.update({
    id: '/debug/review-count-animations',
    path: '/debug/review-count-animations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DebugKbdRoute = DebugKbdRouteImport.update({
  id: '/debug/kbd',
  path: '/debug/kbd',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugEmptyStatesRoute = DebugEmptyStatesRouteImport.update({
  id: '/debug/empty-states',
  path: '/debug/empty-states',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugDesignSystemRoute = DebugDesignSystemRouteImport.update({
  id: '/debug/design-system',
  path: '/debug/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugCodeBlockRoute = DebugCodeBlockRouteImport.update({
  id: '/debug/code-block',
  path: '/debug/code-block',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReturnToAppRoute = AuthReturnToAppRouteImport.update({
  id: '/auth/return-to-app',
  path: '/auth/return-to-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageSplatRoute = ApiStorageSplatRouteImport.update({
  id: '/api/storage/$',
  path: '/api/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionItemsRoute = ApiExtensionItemsRouteImport.update({
  id: '/api/extension/items',
  path: '/api/extension/items',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-error': typeof DevErrorRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/version': typeof VersionRoute
  '/version.json': typeof VersionDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/ask': typeof ApiAskRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/return-to-app': typeof AuthReturnToAppRoute
  '/debug/code-block': typeof DebugCodeBlockRoute
  '/debug/design-system': typeof DebugDesignSystemRoute
  '/debug/empty-states': typeof DebugEmptyStatesRoute
  '/debug/kbd': typeof DebugKbdRoute
  '/debug/review-count-animations': typeof DebugReviewCountAnimationsRoute
  '/debug/review-dialogs': typeof DebugReviewDialogsRoute
  '/debug/review-session-preview': typeof DebugReviewSessionPreviewRoute
  '/debug/review-summary-preview': typeof DebugReviewSummaryPreviewRoute
  '/debug/spinners': typeof DebugSpinnersRoute
  '/debug/suggested-cards': typeof DebugSuggestedCardsRoute
  '/debug/toasts': typeof DebugToastsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/review/$sessionId': typeof ReviewSessionIdRoute
  '/debug/': typeof DebugIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/api/extension/items': typeof ApiExtensionItemsRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-error': typeof DevErrorRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/version': typeof VersionRoute
  '/version.json': typeof VersionDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/ask': typeof ApiAskRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/return-to-app': typeof AuthReturnToAppRoute
  '/debug/code-block': typeof DebugCodeBlockRoute
  '/debug/design-system': typeof DebugDesignSystemRoute
  '/debug/empty-states': typeof DebugEmptyStatesRoute
  '/debug/kbd': typeof DebugKbdRoute
  '/debug/review-count-animations': typeof DebugReviewCountAnimationsRoute
  '/debug/review-dialogs': typeof DebugReviewDialogsRoute
  '/debug/review-session-preview': typeof DebugReviewSessionPreviewRoute
  '/debug/review-summary-preview': typeof DebugReviewSummaryPreviewRoute
  '/debug/spinners': typeof DebugSpinnersRoute
  '/debug/suggested-cards': typeof DebugSuggestedCardsRoute
  '/debug/toasts': typeof DebugToastsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/review/$sessionId': typeof ReviewSessionIdRoute
  '/debug': typeof DebugIndexRoute
  '/review': typeof ReviewIndexRoute
  '/api/extension/items': typeof ApiExtensionItemsRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-error': typeof DevErrorRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/version': typeof VersionRoute
  '/version.json': typeof VersionDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/ask': typeof ApiAskRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/return-to-app': typeof AuthReturnToAppRoute
  '/debug/code-block': typeof DebugCodeBlockRoute
  '/debug/design-system': typeof DebugDesignSystemRoute
  '/debug/empty-states': typeof DebugEmptyStatesRoute
  '/debug/kbd': typeof DebugKbdRoute
  '/debug/review-count-animations': typeof DebugReviewCountAnimationsRoute
  '/debug/review-dialogs': typeof DebugReviewDialogsRoute
  '/debug/review-session-preview': typeof DebugReviewSessionPreviewRoute
  '/debug/review-summary-preview': typeof DebugReviewSummaryPreviewRoute
  '/debug/spinners': typeof DebugSpinnersRoute
  '/debug/suggested-cards': typeof DebugSuggestedCardsRoute
  '/debug/toasts': typeof DebugToastsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/review/$sessionId': typeof ReviewSessionIdRoute
  '/debug/': typeof DebugIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/api/extension/items': typeof ApiExtensionItemsRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-error'
    | '/login'
    | '/settings'
    | '/version'
    | '/version.json'
    | '/.well-known/oauth-protected-resource'
    | '/api/ask'
    | '/api/mcp'
    | '/auth/callback'
    | '/auth/return-to-app'
    | '/debug/code-block'
    | '/debug/design-system'
    | '/debug/empty-states'
    | '/debug/kbd'
    | '/debug/review-count-animations'
    | '/debug/review-dialogs'
    | '/debug/review-session-preview'
    | '/debug/review-summary-preview'
    | '/debug/spinners'
    | '/debug/suggested-cards'
    | '/debug/toasts'
    | '/oauth/consent'
    | '/review/$sessionId'
    | '/debug/'
    | '/review/'
    | '/api/extension/items'
    | '/api/storage/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-error'
    | '/login'
    | '/settings'
    | '/version'
    | '/version.json'
    | '/.well-known/oauth-protected-resource'
    | '/api/ask'
    | '/api/mcp'
    | '/auth/callback'
    | '/auth/return-to-app'
    | '/debug/code-block'
    | '/debug/design-system'
    | '/debug/empty-states'
    | '/debug/kbd'
    | '/debug/review-count-animations'
    | '/debug/review-dialogs'
    | '/debug/review-session-preview'
    | '/debug/review-summary-preview'
    | '/debug/spinners'
    | '/debug/suggested-cards'
    | '/debug/toasts'
    | '/oauth/consent'
    | '/review/$sessionId'
    | '/debug'
    | '/review'
    | '/api/extension/items'
    | '/api/storage/$'
  id:
    | '__root__'
    | '/'
    | '/dev-error'
    | '/login'
    | '/settings'
    | '/version'
    | '/version.json'
    | '/.well-known/oauth-protected-resource'
    | '/api/ask'
    | '/api/mcp'
    | '/auth/callback'
    | '/auth/return-to-app'
    | '/debug/code-block'
    | '/debug/design-system'
    | '/debug/empty-states'
    | '/debug/kbd'
    | '/debug/review-count-animations'
    | '/debug/review-dialogs'
    | '/debug/review-session-preview'
    | '/debug/review-summary-preview'
    | '/debug/spinners'
    | '/debug/suggested-cards'
    | '/debug/toasts'
    | '/oauth/consent'
    | '/review/$sessionId'
    | '/debug/'
    | '/review/'
    | '/api/extension/items'
    | '/api/storage/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevErrorRoute: typeof DevErrorRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  VersionRoute: typeof VersionRoute
  VersionDotjsonRoute: typeof VersionDotjsonRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiMcpRoute: typeof ApiMcpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthReturnToAppRoute: typeof AuthReturnToAppRoute
  DebugCodeBlockRoute: typeof DebugCodeBlockRoute
  DebugDesignSystemRoute: typeof DebugDesignSystemRoute
  DebugEmptyStatesRoute: typeof DebugEmptyStatesRoute
  DebugKbdRoute: typeof DebugKbdRoute
  DebugReviewCountAnimationsRoute: typeof DebugReviewCountAnimationsRoute
  DebugReviewDialogsRoute: typeof DebugReviewDialogsRoute
  DebugReviewSessionPreviewRoute: typeof DebugReviewSessionPreviewRoute
  DebugReviewSummaryPreviewRoute: typeof DebugReviewSummaryPreviewRoute
  DebugSpinnersRoute: typeof DebugSpinnersRoute
  DebugSuggestedCardsRoute: typeof DebugSuggestedCardsRoute
  DebugToastsRoute: typeof DebugToastsRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ReviewSessionIdRoute: typeof ReviewSessionIdRoute
  DebugIndexRoute: typeof DebugIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  ApiExtensionItemsRoute: typeof ApiExtensionItemsRoute
  ApiStorageSplatRoute: typeof ApiStorageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version.json': {
      id: '/version.json'
      path: '/version.json'
      fullPath: '/version.json'
      preLoaderRoute: typeof VersionDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version': {
      id: '/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof VersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-error': {
      id: '/dev-error'
      path: '/dev-error'
      fullPath: '/dev-error'
      preLoaderRoute: typeof DevErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/': {
      id: '/debug/'
      path: '/debug'
      fullPath: '/debug/'
      preLoaderRoute: typeof DebugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$sessionId': {
      id: '/review/$sessionId'
      path: '/review/$sessionId'
      fullPath: '/review/$sessionId'
      preLoaderRoute: typeof ReviewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/toasts': {
      id: '/debug/toasts'
      path: '/debug/toasts'
      fullPath: '/debug/toasts'
      preLoaderRoute: typeof DebugToastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/suggested-cards': {
      id: '/debug/suggested-cards'
      path: '/debug/suggested-cards'
      fullPath: '/debug/suggested-cards'
      preLoaderRoute: typeof DebugSuggestedCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/spinners': {
      id: '/debug/spinners'
      path: '/debug/spinners'
      fullPath: '/debug/spinners'
      preLoaderRoute: typeof DebugSpinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/review-summary-preview': {
      id: '/debug/review-summary-preview'
      path: '/debug/review-summary-preview'
      fullPath: '/debug/review-summary-preview'
      preLoaderRoute: typeof DebugReviewSummaryPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/review-session-preview': {
      id: '/debug/review-session-preview'
      path: '/debug/review-session-preview'
      fullPath: '/debug/review-session-preview'
      preLoaderRoute: typeof DebugReviewSessionPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/review-dialogs': {
      id: '/debug/review-dialogs'
      path: '/debug/review-dialogs'
      fullPath: '/debug/review-dialogs'
      preLoaderRoute: typeof DebugReviewDialogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/review-count-animations': {
      id: '/debug/review-count-animations'
      path: '/debug/review-count-animations'
      fullPath: '/debug/review-count-animations'
      preLoaderRoute: typeof DebugReviewCountAnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/kbd': {
      id: '/debug/kbd'
      path: '/debug/kbd'
      fullPath: '/debug/kbd'
      preLoaderRoute: typeof DebugKbdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/empty-states': {
      id: '/debug/empty-states'
      path: '/debug/empty-states'
      fullPath: '/debug/empty-states'
      preLoaderRoute: typeof DebugEmptyStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/design-system': {
      id: '/debug/design-system'
      path: '/debug/design-system'
      fullPath: '/debug/design-system'
      preLoaderRoute: typeof DebugDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/code-block': {
      id: '/debug/code-block'
      path: '/debug/code-block'
      fullPath: '/debug/code-block'
      preLoaderRoute: typeof DebugCodeBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/return-to-app': {
      id: '/auth/return-to-app'
      path: '/auth/return-to-app'
      fullPath: '/auth/return-to-app'
      preLoaderRoute: typeof AuthReturnToAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/$': {
      id: '/api/storage/$'
      path: '/api/storage/$'
      fullPath: '/api/storage/$'
      preLoaderRoute: typeof ApiStorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/items': {
      id: '/api/extension/items'
      path: '/api/extension/items'
      fullPath: '/api/extension/items'
      preLoaderRoute: typeof ApiExtensionItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevErrorRoute: DevErrorRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  VersionRoute: VersionRoute,
  VersionDotjsonRoute: VersionDotjsonRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiAskRoute: ApiAskRoute,
  ApiMcpRoute: ApiMcpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthReturnToAppRoute: AuthReturnToAppRoute,
  DebugCodeBlockRoute: DebugCodeBlockRoute,
  DebugDesignSystemRoute: DebugDesignSystemRoute,
  DebugEmptyStatesRoute: DebugEmptyStatesRoute,
  DebugKbdRoute: DebugKbdRoute,
  DebugReviewCountAnimationsRoute: DebugReviewCountAnimationsRoute,
  DebugReviewDialogsRoute: DebugReviewDialogsRoute,
  DebugReviewSessionPreviewRoute: DebugReviewSessionPreviewRoute,
  DebugReviewSummaryPreviewRoute: DebugReviewSummaryPreviewRoute,
  DebugSpinnersRoute: DebugSpinnersRoute,
  DebugSuggestedCardsRoute: DebugSuggestedCardsRoute,
  DebugToastsRoute: DebugToastsRoute,
  OauthConsentRoute: OauthConsentRoute,
  ReviewSessionIdRoute: ReviewSessionIdRoute,
  DebugIndexRoute: DebugIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  ApiExtensionItemsRoute: ApiExtensionItemsRoute,
  ApiStorageSplatRoute: ApiStorageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
