import {
  IconAbc,
  IconAdjustments,
  IconAnchor,
  IconAntenna,
  IconApple,
  IconArchive,
  IconArrowRight,
  IconArrowsExchange,
  IconArticle,
  IconAtom,
  IconAtom2,
  IconAward,
  IconBackpack,
  IconBallpen,
  IconBanana,
  IconBeach,
  IconBeer,
  IconBike,
  IconBinary,
  IconBolt,
  IconBone,
  IconBook,
  IconBook2,
  IconBookmark,
  IconBookmarkFilled,
  IconBookmarks,
  IconBox,
  IconBrain,
  IconBrandGithub,
  IconBrandOpenai,
  IconBrandPython,
  IconBrandReact,
  IconBrandTypescript,
  IconBrandX,
  IconBrandYoutube,
  IconBread,
  IconBriefcase,
  IconBroadcast,
  IconBubble,
  IconBulb,
  IconBulbFilled,
  IconBuilding,
  IconBuildingArch,
  IconBuildingBank,
  IconBuildingChurch,
  IconBuildingFactory,
  IconBuildingLighthouse,
  IconBuildingMosque,
  IconCake,
  IconCalendar,
  IconCamera,
  IconCar,
  IconCarrot,
  IconCash,
  IconChartBar,
  IconChartDots,
  IconChartLine,
  IconCheck,
  IconCheese,
  IconChefHat,
  IconChess,
  IconChessKnight,
  IconCircle,
  IconCircuitDiode,
  IconClipboardText,
  IconClock,
  IconCloud,
  IconCode,
  IconCoffee,
  IconCoin,
  IconCoinBitcoin,
  IconCompass,
  IconCpu,
  IconCreditCard,
  IconCube,
  IconDatabase,
  IconDeviceLaptop,
  IconDeviceTv,
  IconDiamond,
  IconDice,
  IconDna,
  IconDog,
  IconEar,
  IconEgg,
  IconEye,
  IconFile,
  IconFileText,
  IconFirstAidKit,
  IconFlag,
  IconFlame,
  IconFlask,
  IconFolder,
  IconFolderFilled,
  IconGavel,
  IconGift,
  IconGlobe,
  IconGraph,
  IconHammer,
  IconHash,
  IconHeadphones,
  IconHeart,
  IconHeartFilled,
  IconHeartbeat,
  IconHexagon,
  IconHistory,
  IconHome,
  IconHourglass,
  IconInbox,
  IconInfinity,
  IconLanguage,
  IconLeaf,
  IconLibrary,
  IconLink,
  IconList,
  IconListFilled,
  IconLungs,
  IconMagnet,
  IconMail,
  IconMap,
  IconMapPin,
  IconMask,
  IconMath,
  IconMeat,
  IconMessage,
  IconMicrophone,
  IconMicroscope,
  IconMoon,
  IconMountain,
  IconMovie,
  IconMusic,
  IconNetwork,
  IconNews,
  IconNote,
  IconNotebook,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPhoto,
  IconPill,
  IconPin,
  IconPinFilled,
  IconPizza,
  IconPlane,
  IconPlanet,
  IconPlant,
  IconPlug,
  IconPuzzle,
  IconPyramid,
  IconQuote,
  IconRadioactive,
  IconReport,
  IconRobot,
  IconRocket,
  IconRoute,
  IconSailboat,
  IconScale,
  IconSchool,
  IconSettings,
  IconShield,
  IconShip,
  IconShoppingBag,
  IconSoup,
  IconSparkles,
  IconStar,
  IconStarFilled,
  IconStars,
  IconStethoscope,
  IconSun,
  IconSword,
  IconTag,
  IconTarget,
  IconTelescope,
  IconTerminal2,
  IconTestPipe,
  IconTheater,
  IconTicket,
  IconTool,
  IconTree,
  IconTrendingUp,
  IconTrophy,
  IconUmbrella,
  IconUsers,
  IconVaccine,
  IconVideo,
  IconVinyl,
  IconVirus,
  IconWallet,
  IconWand,
  IconWaveSquare,
  IconWifi,
  IconWorld,
  IconZzz,
  type Icon,
} from "@tabler/icons-react";

export type ListIconEntry = {
  name: string;
  Component: Icon;
  keywords: string;
};

export const LIST_ICONS: ListIconEntry[] = [
  { name: "List", Component: IconListFilled, keywords: "list default" },
  { name: "ListOutline", Component: IconList, keywords: "list outline" },
  { name: "Inbox", Component: IconInbox, keywords: "inbox tray" },
  { name: "Archive", Component: IconArchive, keywords: "archive box storage" },
  { name: "Star", Component: IconStarFilled, keywords: "star favorite pin" },
  { name: "StarOutline", Component: IconStar, keywords: "star favorite outline" },
  { name: "Heart", Component: IconHeartFilled, keywords: "heart love favorite" },
  { name: "HeartOutline", Component: IconHeart, keywords: "heart love outline" },
  { name: "Bookmark", Component: IconBookmarkFilled, keywords: "bookmark save" },
  { name: "BookmarkOutline", Component: IconBookmark, keywords: "bookmark save outline" },
  { name: "Pin", Component: IconPinFilled, keywords: "pin sticky" },
  { name: "PinOutline", Component: IconPin, keywords: "pin sticky outline" },
  { name: "Folder", Component: IconFolderFilled, keywords: "folder group" },
  { name: "FolderOutline", Component: IconFolder, keywords: "folder group outline" },
  { name: "Book", Component: IconBook, keywords: "book reading" },
  { name: "Book2", Component: IconBook2, keywords: "book reading library" },
  { name: "Notebook", Component: IconNotebook, keywords: "notebook journal" },
  { name: "Note", Component: IconNote, keywords: "note paper" },
  { name: "FileText", Component: IconFileText, keywords: "file document paper" },
  { name: "File", Component: IconFile, keywords: "file document" },
  { name: "Mail", Component: IconMail, keywords: "mail email letter" },
  { name: "Message", Component: IconMessage, keywords: "message chat" },
  { name: "Bubble", Component: IconBubble, keywords: "bubble chat speech" },
  { name: "Link", Component: IconLink, keywords: "link url chain" },
  { name: "Paperclip", Component: IconPaperclip, keywords: "paperclip attach" },
  { name: "Tag", Component: IconTag, keywords: "tag label" },
  { name: "Flag", Component: IconFlag, keywords: "flag mark important" },
  { name: "Check", Component: IconCheck, keywords: "check done complete" },
  { name: "Circle", Component: IconCircle, keywords: "circle dot bullet" },
  { name: "Diamond", Component: IconDiamond, keywords: "diamond gem" },
  { name: "Flame", Component: IconFlame, keywords: "flame fire hot" },
  { name: "Bolt", Component: IconBolt, keywords: "bolt lightning fast" },
  { name: "Sparkles", Component: IconSparkles, keywords: "sparkles magic ai" },
  { name: "Wand", Component: IconWand, keywords: "wand magic" },
  { name: "Rocket", Component: IconRocket, keywords: "rocket launch fast" },
  { name: "Target", Component: IconTarget, keywords: "target goal aim" },
  { name: "Trophy", Component: IconTrophy, keywords: "trophy win award" },
  { name: "Gift", Component: IconGift, keywords: "gift present" },
  { name: "Eye", Component: IconEye, keywords: "eye watch read" },
  { name: "Clock", Component: IconClock, keywords: "clock time later" },
  { name: "Hourglass", Component: IconHourglass, keywords: "hourglass wait time" },
  { name: "Calendar", Component: IconCalendar, keywords: "calendar date schedule" },
  { name: "Zzz", Component: IconZzz, keywords: "zzz sleep later defer" },
  { name: "Brain", Component: IconBrain, keywords: "brain ai mind think neuro intelligence cognition" },
  { name: "Atom", Component: IconAtom, keywords: "atom science physics chemistry molecule" },
  { name: "Atom2", Component: IconAtom2, keywords: "atom electron orbital science" },
  { name: "Robot", Component: IconRobot, keywords: "robot ai automation bot" },
  { name: "Circuit", Component: IconCircuitDiode, keywords: "circuit electronics chip hardware" },
  { name: "OpenAI", Component: IconBrandOpenai, keywords: "openai gpt llm ai chatgpt" },
  { name: "WaveSquare", Component: IconWaveSquare, keywords: "wave signal frequency model neural" },
  { name: "Microscope", Component: IconMicroscope, keywords: "microscope science biology research lab" },
  { name: "TestPipe", Component: IconTestPipe, keywords: "test pipe chemistry lab experiment science" },
  { name: "Flask", Component: IconFlask, keywords: "flask chemistry lab science experiment" },
  { name: "Dna", Component: IconDna, keywords: "dna biology genetics gene science" },
  { name: "Magnet", Component: IconMagnet, keywords: "magnet physics magnetism science" },
  { name: "Radioactive", Component: IconRadioactive, keywords: "radioactive nuclear physics science" },
  { name: "Virus", Component: IconVirus, keywords: "virus biology disease health science" },
  { name: "Telescope", Component: IconTelescope, keywords: "telescope astronomy space science stars" },
  { name: "Pyramid", Component: IconPyramid, keywords: "pyramid geometry math 3d" },
  { name: "Hexagon", Component: IconHexagon, keywords: "hexagon shape geometry" },
  { name: "Cube", Component: IconCube, keywords: "cube 3d geometry shape" },
  { name: "Stars", Component: IconStars, keywords: "stars constellation astronomy multiple" },
  { name: "Math", Component: IconMath, keywords: "math equation formula calculation" },
  { name: "Infinity", Component: IconInfinity, keywords: "infinity math forever loop" },
  { name: "Binary", Component: IconBinary, keywords: "binary code computing data" },
  { name: "ChartLine", Component: IconChartLine, keywords: "chart line graph trend data stats" },
  { name: "ChartDots", Component: IconChartDots, keywords: "chart dots scatter plot data" },
  { name: "Bulb", Component: IconBulbFilled, keywords: "bulb idea light insight" },
  { name: "BulbOutline", Component: IconBulb, keywords: "bulb idea light insight outline" },
  { name: "Network", Component: IconNetwork, keywords: "network graph connections nodes" },
  { name: "Code", Component: IconCode, keywords: "code programming" },
  { name: "Terminal", Component: IconTerminal2, keywords: "terminal cli code" },
  { name: "Cpu", Component: IconCpu, keywords: "cpu chip computer" },
  { name: "Database", Component: IconDatabase, keywords: "database storage" },
  { name: "Laptop", Component: IconDeviceLaptop, keywords: "laptop computer device" },
  { name: "Tv", Component: IconDeviceTv, keywords: "tv video watch" },
  { name: "Movie", Component: IconMovie, keywords: "movie film video" },
  { name: "Video", Component: IconVideo, keywords: "video play" },
  { name: "Camera", Component: IconCamera, keywords: "camera photo" },
  { name: "Microphone", Component: IconMicrophone, keywords: "microphone audio podcast" },
  { name: "Music", Component: IconMusic, keywords: "music audio song" },
  { name: "Palette", Component: IconPalette, keywords: "palette art design" },
  { name: "Pencil", Component: IconPencil, keywords: "pencil edit write" },
  { name: "Ballpen", Component: IconBallpen, keywords: "pen write" },
  { name: "Tool", Component: IconTool, keywords: "tool wrench fix" },
  { name: "Settings", Component: IconSettings, keywords: "settings gear" },
  { name: "Puzzle", Component: IconPuzzle, keywords: "puzzle piece" },
  { name: "Graph", Component: IconGraph, keywords: "graph chart data" },
  { name: "Chart", Component: IconChartBar, keywords: "chart bar stats" },
  { name: "Box", Component: IconBox, keywords: "box package" },
  { name: "Briefcase", Component: IconBriefcase, keywords: "briefcase work job" },
  { name: "ShoppingBag", Component: IconShoppingBag, keywords: "shopping bag buy" },
  { name: "Coffee", Component: IconCoffee, keywords: "coffee cafe drink" },
  { name: "Chef", Component: IconChefHat, keywords: "chef cooking food" },
  { name: "Plane", Component: IconPlane, keywords: "plane travel" },
  { name: "Map", Component: IconMap, keywords: "map location" },
  { name: "Compass", Component: IconCompass, keywords: "compass navigation" },
  { name: "Route", Component: IconRoute, keywords: "route path direction" },
  { name: "Home", Component: IconHome, keywords: "home house" },
  { name: "Globe", Component: IconGlobe, keywords: "globe world earth" },
  { name: "World", Component: IconWorld, keywords: "world planet earth" },
  { name: "Planet", Component: IconPlanet, keywords: "planet space" },
  { name: "Cloud", Component: IconCloud, keywords: "cloud weather" },
  { name: "Sun", Component: IconSun, keywords: "sun day light" },
  { name: "Moon", Component: IconMoon, keywords: "moon night" },
  { name: "Beach", Component: IconBeach, keywords: "beach vacation" },
  { name: "Mountain", Component: IconMountain, keywords: "mountain outdoor" },
  { name: "Tree", Component: IconTree, keywords: "tree nature plant" },
  { name: "Plant", Component: IconPlant, keywords: "plant grow" },
  { name: "Leaf", Component: IconLeaf, keywords: "leaf nature green" },
  { name: "Umbrella", Component: IconUmbrella, keywords: "umbrella rain" },
  { name: "Dog", Component: IconDog, keywords: "dog pet animal" },
  { name: "School", Component: IconSchool, keywords: "school study learn" },
  { name: "Users", Component: IconUsers, keywords: "users people team" },
  { name: "ArrowRight", Component: IconArrowRight, keywords: "arrow next direction" },
  { name: "Shield", Component: IconShield, keywords: "shield security safe" },
  // News, writing, knowledge
  { name: "News", Component: IconNews, keywords: "news article newspaper journal" },
  { name: "Article", Component: IconArticle, keywords: "article post essay text" },
  { name: "Report", Component: IconReport, keywords: "report document paper" },
  { name: "Library", Component: IconLibrary, keywords: "library books collection" },
  { name: "Bookmarks", Component: IconBookmarks, keywords: "bookmarks saved collection" },
  { name: "Quote", Component: IconQuote, keywords: "quote citation reference" },
  { name: "Clipboard", Component: IconClipboardText, keywords: "clipboard notes paste list" },
  { name: "History", Component: IconHistory, keywords: "history time past archive" },
  { name: "Abc", Component: IconAbc, keywords: "abc letters alphabet language" },
  { name: "Language", Component: IconLanguage, keywords: "language translate words" },
  { name: "Hash", Component: IconHash, keywords: "hash tag number pound" },
  { name: "Backpack", Component: IconBackpack, keywords: "backpack school study bag" },
  // Brands / dev
  { name: "GitHub", Component: IconBrandGithub, keywords: "github git repo code" },
  { name: "React", Component: IconBrandReact, keywords: "react frontend framework" },
  { name: "Python", Component: IconBrandPython, keywords: "python programming language" },
  { name: "TypeScript", Component: IconBrandTypescript, keywords: "typescript ts programming" },
  { name: "X", Component: IconBrandX, keywords: "x twitter social" },
  { name: "YouTube", Component: IconBrandYoutube, keywords: "youtube video watch" },
  // Hardware / connectivity
  { name: "Broadcast", Component: IconBroadcast, keywords: "broadcast signal radio" },
  { name: "Antenna", Component: IconAntenna, keywords: "antenna signal radio" },
  { name: "Wifi", Component: IconWifi, keywords: "wifi network signal" },
  { name: "Plug", Component: IconPlug, keywords: "plug power connect" },
  // Money / business
  { name: "Coin", Component: IconCoin, keywords: "coin money currency" },
  { name: "Bitcoin", Component: IconCoinBitcoin, keywords: "bitcoin crypto money" },
  { name: "Cash", Component: IconCash, keywords: "cash money wallet" },
  { name: "Wallet", Component: IconWallet, keywords: "wallet money payment" },
  { name: "CreditCard", Component: IconCreditCard, keywords: "credit card payment money" },
  { name: "Bank", Component: IconBuildingBank, keywords: "bank finance money" },
  { name: "TrendingUp", Component: IconTrendingUp, keywords: "trending up growth chart" },
  { name: "Exchange", Component: IconArrowsExchange, keywords: "exchange swap trade transfer" },
  // Health / medical
  { name: "Heartbeat", Component: IconHeartbeat, keywords: "heartbeat health medical pulse" },
  { name: "Stethoscope", Component: IconStethoscope, keywords: "stethoscope medical doctor" },
  { name: "FirstAid", Component: IconFirstAidKit, keywords: "first aid medical health emergency" },
  { name: "Pill", Component: IconPill, keywords: "pill medicine drug health" },
  { name: "Vaccine", Component: IconVaccine, keywords: "vaccine syringe medical" },
  { name: "Lungs", Component: IconLungs, keywords: "lungs body anatomy health" },
  { name: "Bone", Component: IconBone, keywords: "bone skeleton anatomy" },
  { name: "Ear", Component: IconEar, keywords: "ear hearing anatomy" },
  // Food
  { name: "Apple", Component: IconApple, keywords: "apple fruit food healthy" },
  { name: "Banana", Component: IconBanana, keywords: "banana fruit food" },
  { name: "Carrot", Component: IconCarrot, keywords: "carrot vegetable food healthy" },
  { name: "Bread", Component: IconBread, keywords: "bread bakery food" },
  { name: "Cheese", Component: IconCheese, keywords: "cheese food dairy" },
  { name: "Egg", Component: IconEgg, keywords: "egg food breakfast" },
  { name: "Meat", Component: IconMeat, keywords: "meat food protein" },
  { name: "Pizza", Component: IconPizza, keywords: "pizza food italian" },
  { name: "Soup", Component: IconSoup, keywords: "soup food bowl" },
  { name: "Cake", Component: IconCake, keywords: "cake dessert celebration" },
  { name: "Beer", Component: IconBeer, keywords: "beer drink alcohol" },
  // Places / buildings
  { name: "Building", Component: IconBuilding, keywords: "building office structure" },
  { name: "Arch", Component: IconBuildingArch, keywords: "arch history architecture" },
  { name: "Church", Component: IconBuildingChurch, keywords: "church religion building" },
  { name: "Mosque", Component: IconBuildingMosque, keywords: "mosque religion building" },
  { name: "Factory", Component: IconBuildingFactory, keywords: "factory industry building" },
  { name: "Lighthouse", Component: IconBuildingLighthouse, keywords: "lighthouse guide ocean tower" },
  { name: "MapPin", Component: IconMapPin, keywords: "map pin location place" },
  // Transport
  { name: "Car", Component: IconCar, keywords: "car drive transport vehicle" },
  { name: "Bike", Component: IconBike, keywords: "bike bicycle transport ride" },
  { name: "Ship", Component: IconShip, keywords: "ship boat ocean transport" },
  { name: "Sailboat", Component: IconSailboat, keywords: "sailboat sailing ocean" },
  { name: "Anchor", Component: IconAnchor, keywords: "anchor ship nautical" },
  // Law, philosophy
  { name: "Scale", Component: IconScale, keywords: "scale law balance justice" },
  { name: "Gavel", Component: IconGavel, keywords: "gavel law court judge" },
  // Games / entertainment
  { name: "Chess", Component: IconChess, keywords: "chess game strategy" },
  { name: "ChessKnight", Component: IconChessKnight, keywords: "chess knight horse game" },
  { name: "Dice", Component: IconDice, keywords: "dice game chance random" },
  { name: "Sword", Component: IconSword, keywords: "sword fight weapon" },
  { name: "Mask", Component: IconMask, keywords: "mask theater drama" },
  { name: "Theater", Component: IconTheater, keywords: "theater drama play stage" },
  { name: "Ticket", Component: IconTicket, keywords: "ticket event admission" },
  { name: "Award", Component: IconAward, keywords: "award medal achievement" },
  // Media
  { name: "Photo", Component: IconPhoto, keywords: "photo picture image" },
  { name: "Headphones", Component: IconHeadphones, keywords: "headphones audio music podcast" },
  { name: "Vinyl", Component: IconVinyl, keywords: "vinyl record music album" },
  // Misc tools
  { name: "Hammer", Component: IconHammer, keywords: "hammer tool build fix" },
  { name: "Adjustments", Component: IconAdjustments, keywords: "adjustments settings controls sliders" },
];

export const LIST_ICON_NAMES = LIST_ICONS.map((entry) => entry.name);

const ICON_BY_NAME = new Map(LIST_ICONS.map((entry) => [entry.name, entry]));

export const isValidIconName = (name: string): boolean => ICON_BY_NAME.has(name);

export const getListIcon = (name: string | null | undefined): Icon => {
  if (!name) return IconListFilled;
  return ICON_BY_NAME.get(name)?.Component ?? IconListFilled;
};
