// Generates app/actions/index.ts (the RPC layer) from the manifest below.
//
//   bun run gen:rpc          — regenerate app/actions/index.ts
//   bun run gen:rpc --check  — exit 1 if the checked-in file drifts from the
//                              manifest (used by `bun run check`)
//
// Why codegen: every wrapper in index.ts is mechanically derivable from
// (module, export name, arity). The dynamic `import()` MUST stay inline inside
// each .handler() callback — TanStack Start's compiler strips handler bodies
// from the client bundle only when it can see the import there, so a runtime
// factory/loop would leak server code into the client. Codegen keeps the
// emitted file shaped exactly like the hand-written original.
//
// Adding a new action: implement it in the impl module (app/actions/*.ts),
// add an entry to the manifest below, then run `bun run gen:rpc`.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface FnEntry {
  name: string;
  /** Zero-argument action: no validator, wrapper takes no args. */
  zeroArg?: boolean;
}

interface Section {
  /** Text of the `// --- ... ---` section header. */
  header: string;
  /** Import specifier of the impl module, e.g. "./items". */
  module: string;
  fns: FnEntry[];
}

const manifest: Section[] = [
  {
    header: "items",
    module: "./items",
    fns: [
      { name: "searchItems" },
      { name: "deleteItem" },
      { name: "fetchPageTitle" },
      { name: "createItem" },
      { name: "updateItem" },
      { name: "setItemRead" },
      { name: "generateItemPreview" },
    ],
  },
  {
    header: "queries",
    module: "./queries",
    fns: [
      { name: "fetchItems", zeroArg: true },
      { name: "fetchItemPreviews", zeroArg: true },
    ],
  },
  {
    header: "settings",
    module: "./settings",
    fns: [{ name: "getSettings", zeroArg: true }, { name: "updateSettings" }],
  },
  {
    header: "flashcards",
    module: "./flashcards",
    fns: [
      { name: "getAllFlashcards", zeroArg: true },
      { name: "updateFlashcard" },
    ],
  },
  {
    header: "reviews",
    module: "./review",
    fns: [{ name: "rateCard" }],
  },
  {
    header: "index",
    module: "./index-content",
    fns: [{ name: "semanticSearch" }, { name: "reindexItem" }],
  },
  {
    header: "version",
    module: "./version",
    fns: [{ name: "getVersionInfo", zeroArg: true }],
  },
];

// --- emission ---

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(repoRoot, "app", "actions", "index.ts");

const implAlias = (module: string): string => {
  const base = module.replace("./", "");
  const camel = base.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase(),
  );
  return `${camel}Impl`;
};

const emitFn = (section: Section, fn: FnEntry): string => {
  const alias = implAlias(section.module);
  const ref = `${alias}.${fn.name}`;
  if (fn.zeroArg) {
    return [
      `const ${fn.name}Fn = createServerFn({ method: "POST" }).handler(() => import("${section.module}").then((m) => m.${fn.name}()));`,
      `export const ${fn.name}: typeof ${ref} = () => ${fn.name}Fn();`,
    ].join("\n");
  }
  const validator = `.validator((args: Parameters<typeof ${ref}>) => args)`;
  return [
    `const ${fn.name}Fn = createServerFn({ method: "POST" })`,
    `  ${validator}`,
    `  .handler(({ data }) => import("${section.module}").then((m) => m.${fn.name}(...data)));`,
    `export const ${fn.name}: typeof ${ref} = (...args) => ${fn.name}Fn({ data: args });`,
  ].join("\n");
};

const generate = async (): Promise<string> => {
  const parts: string[] = [];

  parts.push(
    `// GENERATED by scripts/gen-rpc.ts — edit the manifest there, then bun run gen:rpc`,
  );
  parts.push(`import { createServerFn } from "@tanstack/react-start";`);
  parts.push("");
  const sortedSections = [...manifest].sort((a, b) =>
    a.module.localeCompare(b.module),
  );
  for (const section of sortedSections) {
    parts.push(
      `import type * as ${implAlias(section.module)} from "${section.module}";`,
    );
  }

  parts.push("");
  parts.push(
    [
      "// RPC layer between client code and the server-only implementations. Each",
      "// exported function keeps the exact signature of its implementation (callers",
      "// are unchanged from the Next.js server-action days); the createServerFn",
      "// handlers dynamically import the impl modules so db/pdf/etc. code never",
      "// reaches the client bundle. Thrown ActionError/UnauthorizedError messages",
      "// serialize across the wire, so mutation error toasts behave as before.",
    ].join("\n"),
  );
  parts.push("");

  for (const section of manifest) {
    parts.push(`// --- ${section.header} ---`);
    parts.push("");
    for (const fn of section.fns) {
      parts.push(emitFn(section, fn));
      parts.push("");
    }
  }

  const raw = parts.join("\n");
  const prettier = await import("prettier");
  const config = await prettier.resolveConfig(outputPath);
  return prettier.format(raw, { ...config, filepath: outputPath });
};

// --- main ---

const main = async () => {
  const generated = await generate();
  const checkMode = process.argv.includes("--check");

  if (checkMode) {
    let current = "";
    try {
      current = readFileSync(outputPath, "utf8");
    } catch {
      // missing file counts as drift
    }
    if (current !== generated) {
      console.error(
        "gen-rpc: app/actions/index.ts is out of date with scripts/gen-rpc.ts — run `bun run gen:rpc`",
      );
      process.exit(1);
    }
    console.log("gen-rpc: app/actions/index.ts is up to date");
    return;
  }

  writeFileSync(outputPath, generated);
  console.log("gen-rpc: wrote app/actions/index.ts");
};

await main();
