// The design tokens for the Mac app, generated from app/globals.css: every
// `oklch()` colour defined in both `:root` and `.dark`, and the radii and
// row heights, as `Theme.generated.swift`. The hand-written Theme.swift
// keeps what has no CSS token (derived colours, shapes, motion).
//
//   bun run mac:tokens          write the Swift file
//   bun run mac:tokens --check  fail when it is stale (part of `bun run check`)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { repoRoot } from "./profiles";

const CSS = join(repoRoot, "app", "globals.css");
const OUT = join(
  repoRoot,
  "mac",
  "Sources",
  "ReadingList",
  "DesignKit",
  "Theme.generated.swift",
);

const block = (css: string, selector: string) => {
  const start = css.indexOf(`\n${selector} {`);
  if (start === -1) throw new Error(`no ${selector} block in globals.css`);
  const end = css.indexOf("\n}", start);
  return css.slice(start, end);
};

type Oklch = { l: number; c: number; h: number; alpha: number };

// `--name: oklch(l c h)` or `oklch(l c h / a)`; multi-line values (shadows)
// never match, which is what we want.
const colours = (text: string) => {
  const found = new Map<string, Oklch>();
  const pattern =
    /--([a-z0-9-]+):\s*oklch\(([\d.]+)\s+([\d.]+)\s+([\d.]+)(?:\s*\/\s*([\d.]+))?\)\s*;/g;
  for (const match of text.matchAll(pattern)) {
    const [, name, l, c, h, alpha] = match;
    if (!name || !l || !c || !h) continue;
    found.set(name, {
      l: Number(l),
      c: Number(c),
      h: Number(h),
      alpha: alpha ? Number(alpha) : 1,
    });
  }
  return found;
};

const lengths = (text: string) => {
  const found = new Map<string, number>();
  for (const match of text.matchAll(/--([a-z0-9-]+):\s*([\d.]+)px\s*;/g)) {
    if (match[1] && match[2]) found.set(match[1], Number(match[2]));
  }
  return found;
};

// `--muted-foreground` → mutedForeground; a few CSS names differ from the
// Swift ones the kit already uses.
const RENAMES: Record<string, string> = {
  "toast-error-bg": "toastErrorBackground",
  "r-control": "radiusControl",
  "r-surface": "radiusSurface",
  "row-height": "rowHeight",
  "sidebar-row-height": "sidebarRowHeight",
};
const swiftName = (name: string) =>
  RENAMES[name] ??
  name.replace(/-([a-z0-9])/g, (_, letter: string) => letter.toUpperCase());

const swiftColour = ({ l, c, h, alpha }: Oklch) =>
  alpha === 1
    ? `oklch(${l}, ${c}, ${h})`
    : `oklch(${l}, ${c}, ${h}, alpha: ${alpha})`;

const css = readFileSync(CSS, "utf8");
const light = colours(block(css, ":root"));
const dark = colours(block(css, ".dark"));
const sizes = lengths(block(css, ":root"));

const lines = [
  "// Generated by scripts/mac-tokens.ts (bun run mac:tokens) from app/globals.css. Do not edit.",
  "//",
  "// Every oklch colour the stylesheet defines for both appearances, and the",
  "// radii and row heights. Theme.swift keeps the rest.",
  "",
  "import SwiftUI",
  "",
  "extension Theme {",
  "    // MARK: Colours",
  "",
];
for (const [name, lightValue] of light) {
  const darkValue = dark.get(name);
  if (!darkValue) continue;
  lines.push(
    `    static let ${swiftName(name)} = dynamic(${swiftColour(lightValue)}, ${swiftColour(darkValue)})`,
  );
}
lines.push("", "    // MARK: Shape and density", "");
for (const name of [
  "r-control",
  "r-surface",
  "row-height",
  "sidebar-row-height",
]) {
  const value = sizes.get(name);
  if (value === undefined) throw new Error(`no --${name} in globals.css`);
  lines.push(`    static let ${swiftName(name)}: CGFloat = ${value}`);
}
lines.push("}", "");

const text = lines.join("\n");
const check = process.argv.includes("--check");
const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : null;
if (current === text) {
  if (!check) console.log(`${OUT} is current`);
  process.exit(0);
}
if (check) {
  console.error(`${OUT} is stale; run \`bun run mac:tokens\``);
  process.exit(1);
}
writeFileSync(OUT, text);
console.log(`wrote ${OUT} (${light.size} colours)`);
